"""Writes stationgod/_methods.py from the repository's catalogue.json: the client's method table (classes, class
rules, effects, paging, durations, declared and required argument names), the catalogue's hash, and one stub per
method on the Methods mixin, so `game.thing_health(reference_ids=[...])` reads like the method it calls.

    py -3.12 clients/python/generate_catalogue.py           write it
    py -3.12 clients/python/generate_catalogue.py --check   exit 1 if it is stale (tests/test_generated.py does this)

Run it whenever catalogue.json changes (the C# tests rewrite catalogue.json from catalogue/).
"""
import hashlib
import json
import keyword
import pprint
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CATALOGUE = HERE.parent.parent / "catalogue.json"
OUTPUT = HERE / "stationgod" / "_methods.py"


def _load_extract():
    # The same extraction the client runs on a fetched catalogue, loaded by path so the package (which imports the
    # generated module) need not import cleanly while it is being generated.
    import importlib.util
    spec = importlib.util.spec_from_file_location("_stationgod_catalogue", HERE / "stationgod" / "catalogue.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.extract


extract = _load_extract()

# Names the Client itself uses; a method of the same name would hide them.
RESERVED = frozenset({
    "call", "call_async", "iterate", "subscribe", "close", "open", "welcome", "level", "on_world_changed", "on_call",
    "on_event", "catalogue", "protocol", "features", "limits", "world", "game_state", "cheat", "connected",
})

_TYPES = {"string": "str", "integer": "int", "number": "float", "boolean": "bool", "array": "list", "object": "dict",
          "null": "None"}


def _annotation(schema):
    kinds = schema.get("type")
    if kinds is None and ("oneOf" in schema or "anyOf" in schema):
        kinds = [branch.get("type") for branch in schema.get("oneOf") or schema.get("anyOf")]
    if isinstance(kinds, str):
        kinds = [kinds]
    names = []
    for kind in kinds or []:
        name = _TYPES.get(kind) if isinstance(kind, str) else None
        if name is None:
            return "object"
        if name not in names:
            names.append(name)
    return " | ".join(names) if names else "object"


def _first_sentence(text, limit=300):
    text = " ".join(text.split())
    end = text.find(". ")
    sentence = text if end < 0 else text[:end + 1]
    return sentence if len(sentence) <= limit else sentence[:limit - 3].rstrip() + "..."


def _python_name(name):
    return name + "_" if keyword.iskeyword(name) or name in ("self", "options") else name


def render(catalogue_bytes):
    catalogue = json.loads(catalogue_bytes.decode("utf-8"))
    table = extract(catalogue)
    digest = "sha256:" + hashlib.sha256(catalogue_bytes).hexdigest()
    read_only = sorted(name for name, entry in table.items()
                       if entry["class"] == "read" and not entry["class_when"] and not entry["effects"]
                       and not entry["protocol"])
    lines = [
        '"""Generated by generate_catalogue.py from catalogue.json. Do not edit; run',
        '`py -3.12 clients/python/generate_catalogue.py` after catalogue.json changes."""',
        "# fmt: off",
        "",
        f"CATALOGUE_HASH = {digest!r}",
        f"MOD_VERSION = {catalogue.get('mod_version')!r}",
        "",
        "# Read class with no class rules and no x-effects: safe to send again whatever the arguments.",
        "READ_ONLY = frozenset(" + pprint.pformat(read_only, width=116, compact=True) + ")",
        "",
        "TABLE = " + pprint.pformat(table, width=116, sort_dicts=False),
        "",
        "",
        "class Methods:",
        '    """One stub per catalogue method: keyword arguments as the catalogue names them (a Python keyword gets a',
        "    trailing underscore: from_), None meaning omitted; **options are the call options (fields, output_file,",
        '    max_bytes, deadline_ms, shape). Each returns the method\'s result, as call() does."""',
        "",
        "    def call(self, method, /, **params):  # provided by Client",
        "        raise NotImplementedError",
    ]
    for method in sorted(catalogue.get("methods") or [], key=lambda entry: entry["name"]):
        if method["name"] not in table:
            continue  # not in the table: answered by the MCP server (x-runs-in sidecar), never by the game
        name = method["name"]
        if name in RESERVED or not name.isidentifier() or keyword.iskeyword(name):
            raise SystemExit(f"catalogue method '{name}' clashes with a Client attribute or a Python keyword")
        properties = (method.get("params") or {}).get("properties") or {}
        required = set((method.get("params") or {}).get("required") or [])
        arguments = []
        passing = []
        documented = []
        for argument, schema in properties.items():
            python = _python_name(argument)
            arguments.append(f"{python}: {_annotation(schema)} | None = None")
            passing.append(f"{argument!r}: {python}")
            documented.append(f"{python}{' (required)' if argument in required else ''}")
        entry = table[name]
        rules = " (other classes at some arguments)" if entry["class_when"] else ""
        signature = ", ".join(["self", "*"] + arguments + ["**options"]) if arguments else "self, **options"
        lines += [
            "",
            f"    def {name}({signature}) -> dict:",
            f'        """{_first_sentence(method.get("description", "")).replace(chr(92), "/")}',
            "",
            f"        Class: {entry['class']}{rules}." + (f" Arguments: {', '.join(documented)}." if documented else ""),
            '        """',
            f"        return self.call({name!r}, **{{{', '.join(passing)}}}, **options)"
            if passing else f"        return self.call({name!r}, **options)",
        ]
    text = "\n".join(lines) + "\n"
    # Long signature lines are fine for a generated file, but keep each stub's docstring inside 120 columns.
    return text


def main(argv):
    text = render(CATALOGUE.read_bytes())
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
    if "--check" in argv:
        if current != text:
            print(f"{OUTPUT} is stale against {CATALOGUE}; run py -3.12 {Path(__file__).name}", file=sys.stderr)
            return 1
        print("up to date")
        return 0
    if current != text:
        OUTPUT.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {OUTPUT}")
    else:
        print("up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
